spring:
  application:
    name: redirect-server
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:redirect-server
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog.yml
  h2:
    console:
      enabled: true
server:
  port: 8080
springdoc:
  api-docs:
    path: /_docs/api
  swagger-ui:
    path: /_docs/swagger
  show-actuator: true
logging:
  group:
    app: "de.sebastianthiele.redirect"
    sql: "org.springframework.jdbc.core,org.hibernate,org.jooq.tools.LoggerListener"
  level:
    root: "info"
    app: "trace"
    web: "debug"
    sql: "trace"
redirect-server:
  http-header-user-agent: User-Agent